# Site settings
title: Intelfolio
phone: (403) 375-9955
email: info@intelfolio.com
url: https://intelfolio.com
description: "Financial INSIGHTs for private companies"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Intelfolio Inc.

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: linkedin
    url:

# Build settings
markdown: kramdown
permalink: pretty
